language: python
sudo: enable
env:
  - CODECLIMATE_REPO_TOKEN=38ca8bc1084e663f84a1cb60ad17533271122412b42eb45c1dd679c81bfab177
python:
  - 2.7
  - 3.5
  - 3.6
services:
  - couchdb
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install -e .
script:
  - pytest -v tests/main_test.py 
  - coverage run --source boxus -m py.test
  - codeclimate-test-reporter
