language: python
sudo: enable
python:
  - 2.6
  - 2.7
  - 3.5
  - 3.6
services:
  - couchdb
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install -e .
script: pytest -v tests/main_test.py 
